Loja/Loja_carro/urls.py
#coding: utf-8
from django.conf.urls import include, url
from django.contrib import admin
from Loja_carro import settings
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^media/(.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^loja/', include('loja_app.urls', namespace="loja")),
]

Loja/loja_app/urls.py
#coding: utf-8
from django.conf.urls import url

from loja_app.views.cadastar_carro import Cadastar_Carro
from loja_app.views.serach import Busca
from loja_app.views.index import Index
from loja_app.views.usuario import Cadastro, Login_usuario, Logout_usuario
from loja_app.views.ver_carro import Ver_carro

urlpatterns = [
    url(r'^index/$', Index.as_view(), name='index'),
    url(r'^search/$', Busca.as_view(), name='Search1'),
    url(r'^cadastro/$', Cadastro.as_view(), name='cadastro'),
    url(r'^login$', Login_usuario.as_view(), name='login'),
    url(r'^logout/$', Logout_usuario.as_view(), name='logout'),
    url(r'^cadastrar_carro/$', Cadastar_Carro.as_view(), name='Cadastar_Carro'),
    url(r'^ver_carro/(?P<id>\d+)/$', Ver_carro.as_view(), name='ver_carro')
]

Loja/loja_app/models/carros.py
from django.db import models


class Carros(models.Model):

    modelo = models.CharField(max_length=200)
    cor =  models.CharField(max_length=200)
    ano =   models.IntegerField(max_length=200)
    preco  =  models.IntegerField(max_length=200)
    descricao =  models.CharField(max_length=200)
    picture = models.ImageField(upload_to="upload/imagem", blank=True)
    ativo= models.BooleanField(default=True)
    marca = models.CharField(max_length=100)

    def __str__(self):
        return self.modelo

Loja/loja_app/models/usuario.py
#coding: utf-8
from django.db import models
from django.contrib.auth.models import User

class Usuario(User):

    '''
    cpf = models.CharField(max_length=11)
    rg = models.CharField(max_length=7)
    orgao_emissor_rg = models.CharField(max_length=6)
    uf_rg = models.CharField(max_length=2)
    data_emissao_rg = models.DateField()
    certidao = models.CharField(max_length=15)
    livro_certidao = models.CharField(max_length=10)
    folha_certidao = models.CharField(max_length=10)
    cartorio_certidao = models.CharField(max_length=10)
    data_nascimento = models.DateField()
    naturalidade = models.CharField(max_length=100)
    uf = models.CharField(max_length=2)
    nacionalidade = models.CharField(max_length=100)
    estado_civil = models.CharField(max_length=100)
    numero_filhos = models.CharField(max_length=2)
    titulo_eleitor = models.CharField(max_length=15)
    zona_titulo = models.CharField(max_length=10)
    secao_titulo = models.CharField(max_length=10)
    certificado_alistamento_militar = models.CharField(max_length=20)
    carteira_reservista = models.CharField(max_length=10)
    profissao = models.CharField(max_length=100)
    local_trabalho = models.CharField(max_length=100)
    genero = models.CharField(max_length=10)
    endereco = models.CharField(max_length=500)
    numero_endereco = models.CharField(max_length=5)
    complemento = models.CharField(max_length=200)
    bairro = models.CharField(max_length=100)
    cidade = models.CharField(max_length=100)
    estado = models.CharField(max_length=100)
    cep = models.CharField(max_length=15)
    telefone_residencial = models.CharField(max_length=10)
    celular = models.CharField(max_length=10)
    telefone_comercial = models.CharField(max_length=10)
    curso_anterior = models.CharField(max_length=200)
    instituicao_curso = models.CharField(max_length=200)
    cidade_curso = models.CharField(max_length=100)
    uf_curso = models.CharField(max_length=2)
    ano_curso = models.CharField(max_length=4)
    rede = models.CharField(max_length=10)
    etnia = models.CharField(max_length=15)
    area_procedencia = models.CharField(max_length=10)
    autorizacao = models.BooleanField()
    fator_rh = models.CharField(max_length=3)
    problemas_saude = models.CharField(max_length=200)
    necessidades_especificas = models.CharField(max_length=100)
    transtorno_global_desenvolvimento = models.CharField(max_length=100)
    alta_habilidade= models.CharField(max_length=5)
    info_curso = models.CharField(max_length=100)
    carteira_trabalho = models.CharField(max_length=3)
    renda_familiar = models.CharField(max_length=50)
    faixa_etaria = models.CharField(max_length=50)
'''

    cpf = models.CharField(max_length=11,unique=True)
    chaveAtivacaoUsuario = models.CharField(max_length=255)


    def __unicode__(self):
        return self.username

Loja/loja_app/forms/Form_Cadastar_Carro.py
from django import forms

from django import forms

from loja_app.models import Carros


class Form_Cadastar_Carro(forms.ModelForm): # uma funcao com o nome PostForm

    class Meta:
        model = Carros
        fields = ('modelo','cor','ano','preco','descricao','picture','marca')

Loja/loja_app/forms/Form_Serach.py
from django import forms

class Search(forms.Form):
	search = forms.CharField(label='Search', widget=forms.TextInput(attrs={'placeholder': 'Search'}))
	search = forms.CharField(label='Search', widget=forms.TextInput(attrs={'placeholder': 'Search'}))

Loja/loja_app/forms/usuario.py
#coding: utf-8
import hashlib
import os

from django import forms
from loja_app.models.usuario import Usuario


class UsuarioForm(forms.ModelForm):

    first_name = forms.CharField(max_length=200,  widget=forms.TextInput(attrs={'class': 'form-control'}), help_text='Nome')
    cpf = forms.CharField(max_length=11,  widget=forms.TextInput(attrs={'class': 'form-control'}), help_text='CPF')
    username = forms.CharField(max_length=200,  widget=forms.TextInput(attrs={'class': 'form-control'}), help_text='Username')
    password = forms.CharField(max_length=32, help_text='Senha', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(max_length=100,widget=forms.TextInput(attrs={'placeholder': 'Informe seu E-mail'}))


    def save(self, commit=True):
        usuario = super(UsuarioForm, self).save(commit=False)
        usuario.set_password(self.cleaned_data['password'])
        if commit:
            usuario.save()
            return usuario

    def save(self, commit=True):
        usuario = super(UsuarioForm, self).save(commit=False)
        usuario.chaveAtivacaoUsuario = hashlib.sha1(os.urandom(128)).hexdigest()
        usuario.set_password(self.cleaned_data.get('password'))
        usuario.is_active = True
        usuario.is_staff = True
        usuario.save()
        usuario.save()
        return usuario




    class Meta:
        model = Usuario
        fields = 'first_name',  'email', 'cpf',  'username', 'password',

Loja/loja_app/views/cadastar_carro.py
#coding: utf-8
from django.shortcuts import render,HttpResponseRedirect
from django.views.generic.base import View

from loja_app.forms.Form_Cadastar_Carro import Form_Cadastar_Carro


class Cadastar_Carro(View):

    template = "Cadastar_Carro.html"
    conteudo = {'form': Form_Cadastar_Carro()}

    def post(self, request):
        form = Form_Cadastar_Carro(request.POST)
        if form.is_valid():
            form.save(commit=True)
            print ("entrou")
            self.conteudo.update({'messengerSucess': 'Cadastrado com Sucesso', 'messengerError': ''})
            #return HttpResponseRedirect('/naiv_app/cadastar_prova/')
        else:
            print(form.errors)
            return render(request, self.template, {'form': form})
        return render(request, self.template, self.conteudo)

    def get(self, request):
        form = Form_Cadastar_Carro()
        return render(request, self.template, {'form': form})

Loja/loja_app/views/index.py
#coding: utf-8
from django.views.generic.base import View
from django.shortcuts import render

from loja_app.models import Carros


class Index(View):

    def get(self, request):

        carros = Carros.objects.all()
        context_dict = {}
        return render(request, 'index.html', {'carros':carros})

Loja/loja_app/views/serach.py
#coding: utf-8
from django.shortcuts import render
from django.views.generic.base import View

from loja_app.forms.Form_Serach import Search

from  loja_app.models import Carros

class Busca(View):

    template = "Search.html"

    def get(self, request):

        lista = Carros.objects.all()
        #lista = {'lista':sorted(lista)}
        #for i in lista:
        #    print(i.pergunta)
        return render(request, self.template, {'lista':lista})

    def post(self, request):

        form = Search(request.POST)
        print(form)
        if form.is_valid():
            var = Carros.objects.all()
            print (var)
        else:


            marca = Carros.objects.filter(marca__contains=request.POST['name'])
            if(len(marca) == 0):
                print ("aquiiii", marca)
                marca = Carros.objects.filter(marca="Kia")
                print("aquiiiiiiiii",marca)


            modelo = Carros.objects.filter(modelo__contains=request.POST['modelo'])
            if (len(modelo) == 0):
                print ("aquiiii", modelo)
                modelo = Carros.objects.filter(modelo="Fusca")
                print("aquiiiiiiiii", modelo)

            ano = request.POST.get('ano')
            ano1 = ano

            preco =request.POST.get('preco')
            preco1 = preco

            #print (preco,ano)

        # modelo e marca
            for i in marca:
                var1 = i.marca
                print(type(i.marca))


            for c in modelo:
                var = (c.marca)
                var_modelo =  (c.modelo)


            for i in marca:
                var1 = i.marca

        var7 = []
        if(var == var1):
            var3 =  Carros.objects.filter(modelo=var_modelo)
            #print ("aqui deu certo", var3)

            for i in var3:
                #print ("ano do banco",type(i.ano))
                #print ("aqui deu certo", i.ativo)
                ano2 = int(ano1)
                preco2 = int(preco1)

                #print ("ano do html", type(ano2))
                if (i.ano >=ano2):
                    print("ano")
                    if (i.preco <= preco2):
                         #print("preco", i.preco,i.ano,i.id)
                         id1 = i.id
                         print (id1)
                         var7.append(id1)
                         #var5 = Carros.objects.filter(id=id1)
                         #for i in var5:
                             #print ("ano var5",i.ano)
                             #var6 = []
                                #var6 = var5





        var5 = Carros.objects.all()

        for i in var5:
            print ("ano var5",i.ano)

                     #carro = []
                     #carro.append(i)
                     #print (carro)
                     #for c in carro:
                     #   print (c.modelo)
        if (len(var7) == 0):
            print ("vazia")
        vari = 0

        var_carro = []
        for i in var5:
            for c in var7:
                if (i.id==c):
                    print(type(c),type(i.id))
                    var_carro.append(i)
        return render(request, self.template, {"var_carro":var_carro,"vari":vari,"var7":var7,'var5':var5,'form':form})

Loja/loja_app/views/usuario.py
#coding: utf-8
from django.views.generic.base import View
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from loja_app.forms.usuario import UsuarioForm
from django.http import HttpResponseRedirect, HttpResponse
from loja_app.models.usuario import Usuario

class Cadastro(View):


    def post(self, request):
        form = UsuarioForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return HttpResponseRedirect('/loja/login')
        else:
            print(form.errors)
            return render(request, 'cadastro.html/', {'form': form})

    def get(self, request):
        form = UsuarioForm()
        return render(request, 'cadastro.html/', {'form': form})





class AtivaCadastro(View):

    template = 'cadastro.html/'
    conteudo = {'form':UsuarioForm()}

    def get (self,request, chaveAtivacao=None):
        self.conteudo.update({'messengerSucess': '', 'messengerError': ''})

        if (chaveAtivacao):
            try:
                usuario = Usuario.objects.get(chaveAtivacaoUsuario=str(chaveAtivacao))
            except:
                usuario = None

            if (usuario):
                if not (usuario.is_active):
                    usuario.is_active = True
                    usuario.save()
                    self.conteudo.update({'messengerSucess': 'Cadastro ativado!'})
                else:
                    self.conteudo.update({'messengerError': 'Chave já foi utilizada!'})

            else:
                self.conteudo.update({'messengerError':'Chave não associada a nenhum Cadastro!'})
        else:
            self.conteudo.update({'messengerError': 'Nenhuma chave informada!'})

        return render(request, self.template, self.conteudo)




class Login_usuario(View):
    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('search/')
            else:
                return HttpResponse("Sua conta esta desativada.")
        else:
            print("Invalid login details: {0}, {1}".format(username, password))
            return HttpResponse("login invalido.")
    def get(self, request):
        return render(request, 'login.html/', {})

class Logout_usuario(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect('/loja/index/')

Loja/loja_app/views/ver_carro.py
#coding: utf-8
from django.views.generic.base import View
from django.shortcuts import render
from  loja_app.models import Carros




class  Ver_carro(View):



    def get(self, request,id):
        print("Entrou")
        post = Carros.objects.get(id=id)
        print(post)

        return render(request, 'ver_carro.html', {'post':post})

Loja/loja_app/templates/Cadastar_Carro.html
{% extends 'base.html' %}

{% block body %}

{% endblock %}





{% load staticfiles %}



{% block body_block %}

    <div class="four wide column centered inverted">


    <form class="ui form" id="category_form"  method= "post" {% if id %} action="."  {% else %} action="{% url 'loja:Cadastar_Carro' %}"{%endif%}>
        {% csrf_token %}

            <section class="eight wide column"></section>

        <h2>Cadastrar Veículo</h2>

                       <h5>Marca</h5>
                        {{ form.marca }}
                        {{form.marca.errors}}

                         <h5>Modelo</h5>
                        {{ form.modelo }}
                        {{form.modelo.errors}}

                          <h5>Cor</h5>
                        {{ form.cor }}
                        {{form.cor.errors}}

                         <h5>Ano</h5>
                        {{ form.ano}}
                        {{form.ano.errors}}

                        <h5>Preco</h5>
                        {{ form.preco}}
                        {{form.preco.errors}}

                        <h5>Descricao</h5>
                        {{ form.descricao}}
                        {{form.descricao.errors}}


                        <h5>Imagem</h5>
                        {{ form.picture}}
                        {{form.picture.errors}}

                        <br>
                        <input name="id" type="hidden" value="{{id_post}}"/>
                        {% if field.errors %}
                        <br>
                            <div id="error" class="ui pointing label top red basic erro">
                                {{ field.errors }}
                            </div>
                        {% endif %}

<br>
 {%if id%}

        <div class="sixteen wide column">
            <button type="submit" class="ui button" name="submit">Salvar</button>
        </div>
{%else%}
           <div class="sixteen wide column">
               <a class="ui red button"  href="/loja/search">Cancelar</a>
               <button type="submit" class="ui green button" name="submit">Salvar</button>
        </div>
        {%endif%}






    </form>
    </div>


{% endblock %}

Loja/loja_app/templates/Menu_Index.html
{% load staticfiles %}

    <div class="left menu">
        <a class="item" href="{% url 'loja:Search1' %}">Home</a>
    </div>
     <div class="right menu">
                    {% if user.is_authenticated %}
                        <a class="item" href="{% url 'loja:Cadastar_Carro' %}">Cadastrar Carro </a>
                        <a class="item" href="{% url 'loja:logout' %}">Logout</a>

                    {% else %}
                        <a class="item" href="{% url 'loja:cadastro' %}">Cadastre-se</a>
                        <a class="item" href="{% url 'loja:login' %}">Login</a>
                    {% endif %}
                </div>
            </div>
        </div>

Loja/loja_app/templates/Search.html
{% extends 'base.html' %}

{% block body %}
    {%  include 'Menu_Index.html' %}
{% endblock %}



{% load staticfiles %}



{% block body_block %}


    <div class="six wide column centered inverted">
    <br>

    <form class="ui form" method="POST" action="{% url 'loja:Search1' %}" class='ui fluid category search'>
        {% csrf_token %}
        <div class="field">
            <label>Tipo do Carro</label>
            <div class="two fields">
                <div class="field">
                    <input name="name"  required=""   class="search fluid" placeholder="Marca"/>
                </div>
                <div class="field">
                    <input name="modelo" required="" class="search fluid" placeholder="Modelo"/>
                </div>
            </div>
        </div>
        <div class="field">
            <label>Especificações</label>
            <div class="two fields">
                <div class="field">
                    <input name="preco" required="" class="search fluid" placeholder="Preço máximo"/>
                </div>
                <div class="field">
                    <input name="ano"  required="" class="search fluid" placeholder="Ano mínimo"/>
                </div>

                <button type="ui submit button" class="ui button"><i class="search icon"></i></button>
            </div>
        </div>
    </form>

    <br>


        {%for c in  var_carro%}
                <div class="ui card">
                    <div class="image">
                        <img class="img-fluid d-block" src="/media/{{ c.picture }}">
                    </div>
                    <div class="content">
                        <a class="header">Marca: {{ c.marca }}</a>
                        <div class="meta">
                            <span class="date">{{ c.ano }}</span>
                        </div>

                        <div class="description">

                            <a>
                                <i class="">R$ </i>
                                {{ c.preco  }}
                            </a>
                        </div>



                    </div>
                    <div class="extra content">
                        <a>
                            <a  href="/loja/ver_carro/{{ c.id }}/" >+ Detalhes</a>
                        </a>
                    </div>
                </div>
        {%endfor%}










    <br>







    <script>

        function myFunction() {
            var input, filter, ul, li, a, i;
            input = document.getElementById("myInput");
            filter = input.value.toUpperCase();
            ul = document.getElementById("myUL");
            li = ul.getElementsByTagName("li");
            for (i = 0; i < li.length; i++) {
                a = li[i].getElementsByTagName("a")[0];
                if (a.innerHTML.toUpperCase().indexOf(filter) > -1) {
                    li[i].style.display = "";
                } else {
                    li[i].style.display = "none";

                }
            }
        }

    </script>



{% endblock %}

Loja/loja_app/templates/base.html
{% load staticfiles %}

<html xml:lang="pt" lang="br">

<head>
	<title> {% block title %} Auto Frota {% endblock %}</title>
	<meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <link rel="stylesheet" type="text/css" href="{% static 'semantic/semantic.min.css' %}">
    <script src="{% static 'semantic/semantic.min.js' %}"></script>
    <script src="{% static 'semantic/semantic.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'naiv.css' %}"/>

</head>

<body>
	<header class="topo ui grid">
        <div ui grid>
            <div class="two wide column">

            </div>
        </div>
        <div ui grid>
            <div class="two wide column">
            <img class="h" src="{% static 'Auto-Frota-Logo.png' %}"/>
        </div>
        </div>
    </header>


    <nav class="ui seconsdary pointing menu">
            {% block body %}{% endblock %}
    </nav>

     <article class="ui grid conteudo">
        {% block body_block %}
        {% endblock %}
    </article>

    <footer class="ui grid footer">
        <div class="two wide column">
            <a href="https://www.facebook.com/"><i class="large facebook icon"></i></a>
            <a href="https://www.instagram.com/"><i class="large instagram icon"></i></a>
        </div>

        <div  class="twelve wide column">
            <p>Rua Santa Catarina, 876 - Floresta, Joinville - SC</p><br>
            <p>Entre em contato: (47) 3436-4975</p>
            <br>
        </div>
        </div>


    </footer>



</body>
</html>

Loja/loja_app/templates/cadastro.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %} Cadastro {% endblock %}

{% block body_block %}
    <div class="four wide column centered inverted">
        <form class="ui form" id="category_form" method="post" action="{% url 'loja:cadastro' %}">
            <h2>Cadastre-se</h2>
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            <div class="eight wide column">
                {{ form.first_name.errors }}
                <h5>{{ form.first_name.help_text }}</h5>
                {{ form.first_name }}<br/>
            </div>

            <div class="field">
                <label for="email">E-mail</label>
                {{ form.email }}
                {{ form.email.errors }}
            </div>
            <div class="four wide column">
                {{ form.cpf.errors }}
                <h5>{{ form.cpf.help_text }}</h5>
                {{ form.cpf }}<br/>
            </div>

            <div class="ten wide column">
                {{ form.username.errors }}
                <h5>{{ form.username.help_text }}</h5>
                {{ form.username }}<br/>
            </div>
            <div class="ten wide column">
                {{ form.password.errors }}
                <h5>{{ form.password.help_text }}</h5>
                {{ form.password }}<br/>
            </div>
         <div class="ten wide row">
             <br>

            </div>
            <div class="sixteen wide column">
                <a class="ui red button" href="/loja/search">Cancelar</a>
                <button type="submit" class="ui green button" name="submit">Cadastrar</button>
            </div>
        </form>
    </div>
    </div>
{% endblock %}

Loja/loja_app/templates/index.html
{% extends 'base.html' %}

{% block body %}
{%  include 'Menu_Index.html' %}
{% endblock %}



{% load staticfiles %}



{% block body_block %}







{% endblock %}

Loja/loja_app/templates/login.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block body_block %}


    <div class="three wide column centered inverted">

    <form class="ui form" id="login_form" method="post" action="{% url 'loja:login' %}">
            {% csrf_token %}
            <h2>Login</h2>
            <div class="field">
                <label>Nome</label>
                <input type="text" name="username" value="" size="50" /><br />
            </div>
            <div class="field">
                <label>Senha</label>
                <input type="password" name="password" value="" size="50" /><br />
            </div>
        <a class="ui red button" href="/loja/search">Cancelar</a>
            <input type="submit" class="ui green button" value="  Entrar  " /><br/><br/><br/>
        </form></div>
{% endblock %}

Loja/loja_app/templates/ver_carro.html
{% extends 'base.html' %}

{% block body %}
{%  include 'Menu_Index.html' %}
    <div class="esapco"></div>
{% endblock %}







{% load staticfiles %}
{% block body_block %}






    <div class="four wide column centered">
    <div class="esapco"></div><br>

            <div class="ui card">
          <div class="image">
             <img class="img-fluid d-block" src="/media/{{ post.picture }}">
          </div>
          <div class="content">
            <a class="header">Marca: {{ post.marca }}</a>
            <div class="meta">
              <span class="date">{{ post.ano }}</span>
            </div>

              <div class="description">
              Modelo: {{ post.modelo }}
            </div>


            <div class="description">
              Descrição: {{ post.descricao }}
            </div>

              <div class="description">
              Cor: {{ post.cor }}
            </div>


          </div>
          <div class="extra content">
            <a>
              <i class="">R$ </i>
              {{ post.preco  }}
            </a>
          </div>
        </div>

    <br>



{% endblock %}

<script>



</script>